// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: metrics.proto

package grpc_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsTunnel_HandleHTTPRequest_FullMethodName = "/MetricsTunnel/HandleHTTPRequest"
)

// MetricsTunnelClient is the client API for MetricsTunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsTunnelClient interface {
	HandleHTTPRequest(ctx context.Context, in *HTTPRequestPayload, opts ...grpc.CallOption) (*HTTPResponsePayload, error)
}

type metricsTunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsTunnelClient(cc grpc.ClientConnInterface) MetricsTunnelClient {
	return &metricsTunnelClient{cc}
}

func (c *metricsTunnelClient) HandleHTTPRequest(ctx context.Context, in *HTTPRequestPayload, opts ...grpc.CallOption) (*HTTPResponsePayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponsePayload)
	err := c.cc.Invoke(ctx, MetricsTunnel_HandleHTTPRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsTunnelServer is the server API for MetricsTunnel service.
// All implementations must embed UnimplementedMetricsTunnelServer
// for forward compatibility.
type MetricsTunnelServer interface {
	HandleHTTPRequest(context.Context, *HTTPRequestPayload) (*HTTPResponsePayload, error)
	mustEmbedUnimplementedMetricsTunnelServer()
}

// UnimplementedMetricsTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsTunnelServer struct{}

func (UnimplementedMetricsTunnelServer) HandleHTTPRequest(context.Context, *HTTPRequestPayload) (*HTTPResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleHTTPRequest not implemented")
}
func (UnimplementedMetricsTunnelServer) mustEmbedUnimplementedMetricsTunnelServer() {}
func (UnimplementedMetricsTunnelServer) testEmbeddedByValue()                       {}

// UnsafeMetricsTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsTunnelServer will
// result in compilation errors.
type UnsafeMetricsTunnelServer interface {
	mustEmbedUnimplementedMetricsTunnelServer()
}

func RegisterMetricsTunnelServer(s grpc.ServiceRegistrar, srv MetricsTunnelServer) {
	// If the following call pancis, it indicates UnimplementedMetricsTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsTunnel_ServiceDesc, srv)
}

func _MetricsTunnel_HandleHTTPRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequestPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsTunnelServer).HandleHTTPRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsTunnel_HandleHTTPRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsTunnelServer).HandleHTTPRequest(ctx, req.(*HTTPRequestPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsTunnel_ServiceDesc is the grpc.ServiceDesc for MetricsTunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsTunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MetricsTunnel",
	HandlerType: (*MetricsTunnelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHTTPRequest",
			Handler:    _MetricsTunnel_HandleHTTPRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
